<a-mixin id="roboto-black" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Black.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-blackItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-BlackItalic.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-bold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Bold.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-boldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-BoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-italic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Italic.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-light" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Light.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-lightItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-LightItalic.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-medium" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Medium.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-mediumItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-MediumItalic.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-regular" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Regular.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-thin" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-Thin.json; shader: msdf"></a-mixin>
<a-mixin id="roboto-thinItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/roboto/Roboto-ThinItalic.json; shader: msdf"></a-mixin>

<a-mixin id="raleway-black" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Black.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-blackItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-BlackItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-bold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Bold.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-boldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-BoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-extraBold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraBold.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-extraBoldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraBoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-extraLight" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraLight.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-extraLightItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraLightItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-italic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Italic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-light" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Light.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-lightItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-LightItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-medium" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Medium.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-mediumItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-MediumItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-regular" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Regular.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-semiBold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-SemiBold.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-semiBoldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-SemiBoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-thin" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Thin.json; shader: msdf"></a-mixin>
<a-mixin id="raleway-thinItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ThinItalic.json; shader: msdf"></a-mixin>