<a-mixin id="font-black" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Black.json; shader: msdf"></a-mixin>
<a-mixin id="font-blackItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-BlackItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-bold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Bold.json; shader: msdf"></a-mixin>
<a-mixin id="font-boldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-BoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-extraBold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraBold.json; shader: msdf"></a-mixin>
<a-mixin id="font-extraBoldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraBoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-extraLight" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraLight.json; shader: msdf"></a-mixin>
<a-mixin id="font-extraLightItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ExtraLightItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-italic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Italic.json; shader: msdf"></a-mixin>
<a-mixin id="font-light" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Light.json; shader: msdf"></a-mixin>
<a-mixin id="font-lightItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-LightItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-medium" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Medium.json; shader: msdf"></a-mixin>
<a-mixin id="font-mediumItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-MediumItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-regular" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Regular.json; shader: msdf"></a-mixin>
<a-mixin id="font-semiBold" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-SemiBold.json; shader: msdf"></a-mixin>
<a-mixin id="font-semiBoldItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-SemiBoldItalic.json; shader: msdf"></a-mixin>
<a-mixin id="font-thin" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-Thin.json; shader: msdf"></a-mixin>
<a-mixin id="font-thinItalic" text="font: https://raw.githubusercontent.com/etiennepinchon/aframe-fonts/master/fonts/raleway/Raleway-ThinItalic.json; shader: msdf"></a-mixin>